//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWebApp.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Music
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music()
        {
            this.Comments = new HashSet<Comment>();
            this.Favorites = new HashSet<Favorite>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public Nullable<int> SingerId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GenresId { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        [JsonProperty("View")]
        public Nullable<int> C_View { get; set; }
    
        public virtual Album Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Singer Singer { get; set; }
        public virtual User User { get; set; }
    }
}
